Alias: $StatusCodeDiagnosticRepport = http://medcomfhir.dk/ig/terminology/ValueSet/medcom-corediagnosticrepport-status
// Alias: $StatusCodeDiagnosticReportSystem = http://hl7.org/fhir/diagnostic-report-status
Alias: $ObsStatusCodes = http://medcomfhir.dk/ig/terminology/ValueSet/medcom-core-observation-status
Alias: $ObsStatusCodeSystem = http://hl7.org/fhir/observation-status
Alias: $ucum = http://unitsofmeasure.org
Alias: $NPUObservationCodesValueSet = http://medcomfhir.dk/ig/terminology/ValueSet/NPUObservationCodesValueSet
Alias: $MessageEvents = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-eventCodes
Alias: $HCOActivityCodes = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes
Alias: $Use = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-destinationUse
Alias: $v3-Confidentiality = http://terminology.hl7.org/CodeSystem/v3-Confidentiality
Alias: $ProducenID = http://medcomfhir.dk/ig/terminology/CodeSystem/MedComProducentID  
Alias: $MunicipalityCodes = http://hl7.dk/fhir/core/ValueSet/dk-core-MunicipalityCodes
Alias: $PractitionerRole = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-PractitionerRolesSKSadministrativ
Alias: $DiagnosticReportCode = http://medcomfhir.dk/ig/terminology/ValueSet/MedComDiagnosticReportCodesValueset
Alias: $DiagnosticReportCodeSystem = http://medcomfhir.dk/ig/terminology/CodeSystem/MedComDiagnosticReportCodes	
Alias: $BundleType = http://hl7.org/fhir/bundle-type
Alias: $Use = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-destinationUse
Alias: $ObsStatusCodeSystem = http://hl7.org/fhir/observation-status
// Alias: $StatusCodeDiagnosticReportSystem = http://hl7.org/fhir/diagnostic-report-status
Alias: $Mimetypes = http://medcomfhir.dk/ig/terminology/ValueSet/medcom-core-attachmentMimeTypes
Alias: $obsInterpretation = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-interpretation-codes
Alias: $mediastatus = http://hl7.org/fhir/event-status
Alias: $MedcomCodes = http://medcomfhir.dk/ig/terminology/ValueSet/MedComObservationValueSet
