@startuml HomeCareObsProfile
hide empty members
top to bottom direction

class "MedComCorePatient" as patient
class "MedComProducerOrganization" as organization 
class "MedComHomeCareDiagnosticReport" as diagnosticReport <<MedComCoreDiagnosticReport>>
class "MedComHomeCareObservation" as coreobservation <<MedComCoreObservation>>

diagnosticReport --> patient : "subject"
diagnosticReport --> organization: "performer"
diagnosticReport --> coreobservation : "result"
coreobservation --> organization:"performer"



@enduml