@startuml HomeCareObservationMessage

hide empty members

top to bottom direction

class "MedComHomeCareMessage" as message <<MedComMessagingMessage>>
class "MedComHomeCareMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingProvenance" as provenance
class "MedComMessagingOrganization" as messagingOrganization <<MedComCoreOrganization>>
class "MedComMessagingOrganizationRequester" as observationRequester 
class "MedComCorePatient" as patient
class "MedComObservationProducerOrganization" as organization
' class "MedComCorePractitioner" as author
class "HomeCareReport" as diagnosticReport <<MedComCoreDiagnosticReport>>
class "HomeCareObservation" as coreobservation <<MedComCoreObservation>>

message -- messageheader : "entry"
messageheader -- diagnosticReport : "focus"
message -- provenance : "entry"
provenance -- messageheader : "target" 
provenance -- messagingOrganization : "agent.who"
diagnosticReport -- patient : "subject"
diagnosticReport -- organization: "performer"
diagnosticReport -- coreobservation : "result"
coreobservation -- organization:"performer"


messageheader -- observationRequester : "receiver"
messageheader -- messagingOrganization : "sender"

@enduml