@startuml HomeCareObservationMessage

hide empty members

top to bottom direction

class "MedComHomeCareObservationMessage" as message <<MedComMessagingMessage>>
class "MedComHomeCareObservationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingProvenance" as provenance
class "MedComMessagingRequesterOrganization" as observationRequester <<MedComMessagingOrganization>>
class "MedComCorePatient" as patient
class "MedComCoreProducerOrganization" as organization 
class "MedComHomeCareDiagnosticReport" as diagnosticReport <<MedComCoreDiagnosticReport>>
class "MedComHomeCareObservation" as coreobservation <<MedComCoreObservation>>
class "MedComMedia" as media

message --> messageheader : "entry"
messageheader --> diagnosticReport : "focus"
messageheader --> organization : "sender"
message --> provenance : "entry"
provenance --> messageheader : "target" 
provenance --> organization : "agent.who"
messageheader --> observationRequester : "receiver"
diagnosticReport --> organization: "performer"
diagnosticReport --> patient : "subject"
diagnosticReport --> coreobservation : "result"
diagnosticReport--> media : "attachment"
coreobservation --> organization:"performer"

@enduml